classDiagram
class util {
    generic utilities
}
class nmtlib {
    source parser, boilerplate generator
}
class nmt {
    command line tool of nmtlib
}
class common {
    common code for the GUI app
}
class nmtapp {
    GUI app logic (the Controller)
}
class qtui {
    Qt implementation of the UI (the View)
}
class nmtqt {
    Qt application (inititializes View and Controller)
}
nmtlib <.. nmt
util <.. nmtlib
common <.. nmtapp
common <.. nmtqt
qtui <.. nmtqt
nmtapp <.. nmtqt
common <.. qtui
nmtlib <.. nmtapp
